apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  # Multi-source: Helm chart + extra manifests in a repo folder
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 37.4.0
      helm:
        releaseName: traefik
        values: |
          additionalArguments:
          - --serversTransport.insecureSkipVerify=true
          - --api.dashboard=true
          - --api.insecure=false
          
          logs:
            general:
              level: DEBUG
            access:
              enabled: true

          deployment:
            additionalContainers: []
            annotations: {}
            enabled: true
            initContainers: []
            podAnnotations: {}
            replicas: 2
          globalArguments:
          - --global.sendanonymoususage=false
          - --global.checknewversion=false
          ingressRoute:
            dashboard:
              enabled: false
          nodeSelector:
            worker: "true"
          ports:
            web:
              redirections:
                entryPoint:
                  permanent: true
                  scheme: https
                  to: websecure
            websecure:
              tls:
                enabled: true
          providers:
            kubernetesCRD:
              allowExternalNameServices: true
              enabled: true
              ingressClass: traefik-external
            kubernetesIngress:
              allowExternalNameServices: true
              ingressClass: traefik-external
              ingressClassByName: true
              enabled: true
              publishedService:
                enabled: true
          rbac:
            enabled: true
          service:
            annotations: {}
            enabled: true
            externalIPs: []
            labels: {}
            loadBalancerSourceRanges: []
            spec:
              loadBalancerIP: 172.16.51.65
            type: LoadBalancer

    - repoURL: https://github.com/gregpakes/homelab
      targetRevision: main
      path: argocd/infrastructure/traefik/certs
      directory:
        recurse: false   # top-level files only

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true