apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-old-longhorn
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 75Gi          # must be <= PV capacity
  storageClassName: longhorn
  volumeName: pvc-269d9577-279c-40da-ae53-43c22af28811   # <-- from kubectl get pv