apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-ceph
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd       # <-- your new Ceph StorageClass
  resources:
    requests:
      storage: 75Gi