# # argocd/infrastructure/volsync-backups/values.yaml

# restic:
#   repositorySecretName: volsync-restic-repo
#   repoStorageClass: smb-backup        # used in the PVC
#   repoDefaultSize: 500Gi
#   cacheCapacity: 10Gi
#   copyMethod: Direct
#   schedule: "0 3 * * *"
#   retain:
#     daily: 7
#     weekly: 4
#     monthly: 3

#   moverSecurityContext:
#     runAsUser: 0
#     runAsGroup: 0
#     fsGroup: 0

# pvcs:
#   - name: bazarr-config-ceph
#     namespace: servarr
#     backupName: bazarr-config
#     schedule: "10 1/3 * * *"   # optional override

#   - name: pihole-ceph
#     namespace: pihole
#     backupName: pihole
#     schedule: "10 2/3 * * *"   # optional override

#   - name: prometheus-monitoring-kube-prometheus-prometheus-db-prometheus-monitoring-kube-prometheus-prometheus-0
#     namespace: monitoring
#     backupName: prometheus
#     schedule: "10 3/3 * * *"   # optional override