# argocd/infrastructure/volsync-backups/values.yaml

restic:
  # Name of the Secret created by the ExternalSecret chart
  repositorySecretName: volsync-restic-repo

  cacheCapacity: 10Gi
  schedule: "0 2 * * *"
  retain:
    daily: 7
    weekly: 4
    monthly: 3
    
pvcs:
  - name: bazarr-config-ceph
    namespace: servarr
    backupName: bazarr-config
    schedule: "0 3 * * *"   # optional override

  # - name: pihole-ceph
  #   namespace: pihole
  #   backupName: pihole
  #   repoSize: 100Gi