# argocd/infrastructure/volsync-backups/values.yaml

restic:
  repositorySecretName: volsync-restic-repo
  repoStorageClass: smb-backup        # used in the PVC
  repoDefaultSize: 500Gi
  cacheCapacity: 10Gi
  copyMethod: Direct
  schedule: "0 3 * * *"
  retain:
    daily: 7
    weekly: 4
    monthly: 3

pvcs:
  - name: bazarr-config-ceph
    namespace: servarr
    backupName: bazarr-config
    schedule: "0 3 * * *"   # optional override

  # - name: pihole-ceph
  #   namespace: pihole
  #   backupName: pihole
  #   repoSize: 100Gi