apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-ceph
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd       # <-- your new Ceph StorageClass
  resources:
    requests:
      storage: 5Gi