apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-f0311832-cedf-4fe6-af93-c70f04935ba6
spec:
  capacity:
    storage: 5Gi                    # must match the Longhorn volume size
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: driver.longhorn.io
    volumeHandle: pvc-f0311832-cedf-4fe6-af93-c70f04935ba6
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi    # <= must be <= PV capacity (5Gi here)
  volumeName: pvc-f0311832-cedf-4fe6-af93-c70f04935ba6