apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: download-clients-qbit-config
  namespace: servarr
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
  volumeName: pvc-5fc31f9d-fbd8-49a2-95fb-026a73d1493e
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: download-clients-nzbget-config
  namespace: servarr
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeName: pvc-ee6c7d98-c0c9-481c-aab8-585cc19d80f2