# configuration:
#   backupStorageLocation:
#     - name: default
#       provider: aws
#       bucket: velero
#       config:
#         region: minio
#         s3ForcePathStyle: "true"
#         s3Url: http://velero-minio-hl.minio-tenant.svc.cluster.local:9000

# credentials:
#   existingSecret: velero-minio-creds

snapshotsEnabled: false

deployNodeAgent: true
defaultVolumesToFsBackup: true

nodeAgent:
  podVolumePath: /var/lib/kubelet/pods

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.13.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins