ceph-csi-rbd:
  csiConfig:
    - clusterID: "d90b0848-9994-451f-b850-04aadfe27951"
      monitors:
        - "172.16.250.10:6789"
        - "172.16.250.11:6789"
        - "172.16.250.12:6789"

  secret:
    create: false
    userID: admin
    userKey: ""          # ignored when create=false

  storageClass:
    create: true
    name: ceph-rbd
    pool: kubernetes
    clusterID: "d90b0848-9994-451f-b850-04aadfe27951"
    annotations: {}
    provisionerSecretName: csi-rbd-secret
    provisionerSecretNamespace: kube-system
    controllerExpandSecretName: csi-rbd-secret
    controllerExpandSecretNamespace: kube-system
    nodeStageSecretName: csi-rbd-secret
    nodeStageSecretNamespace: kube-system